### ISSUE TITLE
Convert JSON Caching into Sqlite DB with SugarORM

### ISSUE THREAD

**Issue by elswenson** [echistyakov/GauchoGrub2#1]
### [Sugar ORM basic docs](https://satyan.github.io/sugar/)
1. Create new folder for models
2. Refactor/remove existing caching methods as necessary to handle the changes
3. Handle the following db objects:
4. MenuItem
5. MenuItemType
6. MenuCategory
7. Meal
8. Menu
9. Rating
10. Favorite

Be sure to document fully using javadoc

**Comment by elswenson** [comment]
May completely overhaul issue in favor of another system, SugarORM cannot handle queries properly for 1-1 or 1-many relationships. There exist other ORM libraries (more complex), that we should use.

**Comment by elswenson** [comment]
Use [Active Android](https://github.com/pardom/ActiveAndroid)

**Comment by echistyakov** [comment]
@elswenson Active Android was meh. I ended up using Requery. Requery is by far the most complex ORM with lots of features (even many-to-many support). It even has an integration with "reactive?" thingy that you keep talking about. A very rough draft of the DB schema is here: #15

**Comment by elswenson** [comment]
@echistyakov It looks better than active android. Definitely a very new ORM. I'm not sure what "reactive" thing you're referring to.

**Comment by elswenson** [comment]
As of now, closing this issue as it is at least handled in a preliminary way via #15
