### ISSUE TITLE
Move BaseActivity Functionality Into MainActivity

### ISSUE THREAD

**Issue by andrewtran1995** [echistyakov/GauchoGrub2#17]
Move functionality into new Navigation Layout activity.

**Comment by elswenson** [comment]
Hold off on this task until I can help define it further, sometime tomorrow..

**Comment by andrewtran1995** [comment]
@elswenson , when do you think you can give me further direction on this? And if not soon, is there something else I should focus on?

**Comment by elswenson** [comment]
Once I figure out an obnoxious bug in 162, I'll be right on it.

**Comment by andrewtran1995** [comment]
Jack's comments over Messenger: 
"So last year, we had a class "BaseActivity" which was essentially our main activity. It had a navigation drawer and wrapped all of the app fragments. This year google introduced a new app layout called "Navigation Layout" which has a navigation drawer functionality and is much better then our "BaseActivity" stuff. A default "MainActivity" class for the new navigation layout (generated by AndroidStudio) is already on develop.

Can you get rid of the BaseActivity in favor of the new MainActivity?

You could check to see if BaseActivity has any relevant code (other than drawer stuff), and copy it over into the MainActivity"

**Comment by elswenson** [comment]
No longer relevant due to the re-organizations in #22 and #23
