### ISSUE TITLE
Update README.md to contain Best Practices

### ISSUE THREAD

**Issue by elswenson** [echistyakov/GauchoGrub2#19]
Readme.md needs to be updated to contain:
-  the determined choices for best practices in #5 
- standards for branch naming
- information from/relating to #13, including some proguard setup information and basic information about the keystore setup

@echistyakov please handle the last part of the aforementioned items to reference in README.md

**Comment by echistyakov** [comment]
@elswenson Done: https://github.com/echistyakov/GauchoGrub2/commit/f55136dc153eef08342b2f3977b77822ec14f64a
