### ISSUE TITLE
Implement SettingsActivity

### ISSUE THREAD

**Issue by elswenson** [echistyakov/GauchoGrub2#20]
Add SettingsActivity and relevant logic (for both the compat activity and regular activity) utilizing [SharedPreferences](http://developer.android.com/reference/android/content/SharedPreferences.html) 

Needs to cover the following options:
1. Default Dining Common (dropdown)
2. Default Dining Common Override via Geolocation (toggle, also disables Default Dining Common)
3. Favorites Notification (toggle)
4. Default Filter for Menu

The default dining commons options should be grouped together following android material design practices.

**Comment by andrewtran1995** [comment]
**For Preference 4:**
How flexible should a filter option be? For example, when discussing vegetarian (v) options, should the user be allowed to specify "Only vegetarian" menu items in addition to "No vegetarian" menu items? Would this extend to other categories: vegan, with nuts?

And if so, how would this be represented on the MultiSelect Preference with array entries "Only vegetarian, No vegetarian, ... "?

**Comment by elswenson** [comment]
I would like to keep everything toggleable using a [MultiSelectListPreference](http://developer.android.com/reference/android/preference/MultiSelectListPreference.html), so everything will need to be boolean. Perhaps the following list or something of the like:
- Has Meat
- Vegetarian
- Vegan
- Contains Nuts
- No Nuts
- Has other allergy warning

**Comment by andrewtran1995** [comment]
I did not take a look at your list until after the pull request -- we can revisit this perhaps after we manage some of the other issues.

**Comment by elswenson** [comment]
Handled in #26
