### ISSUE TITLE
Implement MenuScraperService

### ISSUE THREAD

**Issue by elswenson** [echistyakov/GauchoGrub2#21]
Create a new Service, potentially an IntentService that can parse the menus from the html page.

**Comment by elswenson** [comment]
## Tasks to complete:
1. Retrieves the HTML using a get request for a specific dining common
2. Parses the HTML
3. Stores the HTML in the sqlite DB using Requery

**Comment by elswenson** [comment]
Part 3 is blocked while we wait for the re-addition of the requery schema and structure.

**Comment by andrewtran1995** [comment]
Just  to clarify, this service would run if the app is opened on a new day or if the app is checking to see if the user's favorites are being served that day?

**Comment by elswenson** [comment]
Mostly correct, that's why it's an IntentService, should be fairly easy to initiate it using an [AlarmManager](http://developer.android.com/reference/android/app/AlarmManager.html)

We would only want to run it every so often when the app is opened, and we need to handle checking for network options, but that's not within the scope of this class, but rather when it is called.

**Comment by andrewtran1995** [comment]
I am thinking of using [Jsoup](http://jsoup.org/) in order to help implement the parser. Thoughts on if it would be appropriate in this situation?

**Comment by echistyakov** [comment]
@andrewtran1995 Sounds good to me.

**Comment by andrewtran1995** [comment]
Will we always be fetching from the current date? Or should I make it such that we can scrape from a given date (e.g. allow a function in MenuScraperService.java accept a Date object)?

**Comment by echistyakov** [comment]
@andrewtran1995 Given date. Users should have the ability to view tomorrow's (or next week's) menus.

**Comment by elswenson** [comment]
Implemented in #34 and #38
