### ISSUE TITLE
Determine Design Practices

### ISSUE THREAD

**Issue by elswenson** [echistyakov/GauchoGrub2#8]
@andrewtran1995 @echistyakov 
1. Determine standards for handling state related information for activities and fragments
2. Determine java variable naming standards
3. Determine xml string variable naming standards
4. Determine xml layout id naming standards

**Comment by andrewtran1995** [comment]
1. State in activities and fragments: 
   keys defined as final strings in all caps "STATE_x"
   where x is the capitalized name of the variable being stored
2. Java variable names: 
   Lower camel case for names
3. XML String resources:
   snake case, separated into segments with comment titles
   
   
   
   ...
4. XML Ids
   JavaClass_LowerCamelCase starts with the name of the relevant Java class
