### ISSUE TITLE
Research Release Practices

### ISSUE THREAD

**Issue by elswenson** [echistyakov/GauchoGrub2#9]
Research Gradle Release practices including minifyEnabled and proguardFiles

**Comment by andrewtran1995** [comment]
Look into Keystore setup and proper usage

**Comment by echistyakov** [comment]
@elswenson Pull request ready: #13
ProGuard is now enabled for release builds. Also, unused resources will be automatically removed. This PR also contains a keystore for release APK signing.

**Comment by elswenson** [comment]
Probably bad practice to be including those files for the keystore, but for the sake of this class and the current purposes of this repo, let's go ahead and do that for simplicity.
